# Generated by Django 4.2.27 on 2026-01-25 12:36

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('total_storage_used', models.BigIntegerField(default=0)),
                ('original_storage_used', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'User Storage Stats',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('is_reference', models.BooleanField(default=False)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='files.file')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id', 'uploaded_at'], name='files_file_user_id_0d661d_idx'), models.Index(fields=['user_id', 'file_type'], name='files_file_user_id_11f2e8_idx'), models.Index(fields=['file_hash'], name='files_file_file_ha_868749_idx'), models.Index(fields=['user_id', 'size'], name='files_file_user_id_891e6c_idx')],
            },
        ),
    ]
